DROP TABLE IF EXISTS menu CASCADE;

CREATE TABLE menu (
  id SERIAL PRIMARY KEY NOT NULL,

  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  food_category VARCHAR(255) NOT NULL,

  item_img TEXT NOT NULL,

  price SMALLINT NOT NULL
);
